### ISSUE TITLE
Banner: Post title must only limit up to 2 lines only

### ISSUE THREAD

**Issue by ricatitan** [titan-cebu/PianoMagic#1]
![image](https://cloud.githubusercontent.com/assets/18568310/15884471/68f65652-2d83-11e6-9c58-2b41b31683b1.png)

![image](https://cloud.githubusercontent.com/assets/18568310/15884473/6ce902be-2d83-11e6-8ccc-eba289c408f2.png)

**Comment by romatitan** [comment]
![image](https://cloud.githubusercontent.com/assets/12888048/16293697/99c03b82-394e-11e6-9c54-3b468eedc0e1.png)
