### ISSUE TITLE
Product Page: Error in Pagination. Must paginate after 9 posts.

### ISSUE THREAD

**Issue by ricatitan** [titan-cebu/PianoMagic#10]
![image](https://cloud.githubusercontent.com/assets/18568310/15916299/de790bb8-2e23-11e6-83c8-b0d66b8562f1.png)

**Comment by ricatitan** [comment]
![image](https://cloud.githubusercontent.com/assets/18568310/16295008/ba3325c0-3956-11e6-8af6-1f6dbbce9b4a.png)

**Comment by romatitan** [comment]
**This is a scope error. Pagination is not possible for product categories.**
