### ISSUE TITLE
Product Listing: Incorrect font style for product title

### ISSUE THREAD

**Issue by ricatitan** [titan-cebu/PianoMagic#11]
![image](https://cloud.githubusercontent.com/assets/18568310/15916447/c1df5578-2e25-11e6-93eb-200b20179ed3.png)

**Comment by romatitan** [comment]
**Kindly check again the font-size. It should be 18px, not 26px.**
![image](https://cloud.githubusercontent.com/assets/12888048/16295094/3c9aca4a-3957-11e6-8e0c-b0f70554a8b0.png)
