### ISSUE TITLE
Search Result Page: Post title must limit upto 1 line only

### ISSUE THREAD

**Issue by ricatitan** [titan-cebu/PianoMagic#26]
![image](https://cloud.githubusercontent.com/assets/18568310/15919727/9131f18a-2e46-11e6-848c-7ba13f1e2a97.png)

**Comment by romatitan** [comment]
![image](https://cloud.githubusercontent.com/assets/12888048/16294576/ec3ccb82-3953-11e6-8aa9-5d7cb308bca6.png)
