### ISSUE TITLE
Sidebar Form: Error form

### ISSUE THREAD

**Issue by ricatitan** [titan-cebu/PianoMagic#5]
![image](https://cloud.githubusercontent.com/assets/18568310/15888700/840c8350-2d9a-11e6-9ef5-a3abf3aa0a18.png)

**Comment by romatitan** [comment]
Kindly check again.
1. Drop down field should have the same height with the text fields.
2. There are 2 arrows in the drop down field.

![image](https://cloud.githubusercontent.com/assets/12888048/16294275/4b752b6e-3952-11e6-9a91-081425d2e67b.png)

**Comment by ricatitan** [comment]
![image](https://cloud.githubusercontent.com/assets/18568310/16366334/965576ae-3c48-11e6-8033-5555ab4a9ef0.png)
